### PR TITLE
Adding tests and support for Django 4.2 - 5x and removing EOL versions of python and django

### LINKED ISSUE #383: Django 4.1 support?
Hi,
The latest version of django-newsletter doesn't work with Django 4.1.
I got this error:

`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'`

I fixed it by replacing deprecated ugettext_lazy to gettext_lazy, but got another error which I don't know how to fix:

`ImportError: Module "compressor.finders" does not define a "CompressorFinder" attribute/class`

### LINKED ISSUE #390: pkg_resources is deprecated in python 3.12
I just upgraded to Python 3.12 and I'm getting a deprecation warning about `pkg_resources`

```
.../newsletter/__init__.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_distribution, DistributionNotFound
```

According to https://setuptools.pypa.io/en/latest/pkg_resources.html it should be replaced by `importlib.resources`:

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

### PR DESCRIPTION
**Pull request by sebastian-muthwill**
Update python and django versions
- dropped tests for Python <3.7
- dropped tests for Django <4.2
- added tests for Python 3.11, 3.12, 3.13
- added tests for Django >=4.2

This PR addresses the following issues:
- fixes #383 
- fixes #390

### CODE REVIEW

**Comment by sebastian-muthwill** [comment]
Created an issue to get the changes released: https://github.com/jazzband/help/issues/383

File: newsletter/models.py
Comment (newearthmartin) [inline newsletter/models.py:1]: What's wrong with LooseVersion? It's better than manually parsing the version number. Please leave like it was unless there is some good reason.

(Also it's better to just remove code instead of leaving it commented)

File: tests/test_web.py
Comment (newearthmartin) [inline tests/test_web.py:1]: Better use a `TEST_PASSWORD` variable if we are going to repeat it all over

File: CHANGES.rst
Comment (newearthmartin) [inline CHANGES.rst:1]: Why are we removing support for those Django versions? What's the reason? Is there something incompatible?

**Review by newearthmartin — CHANGES_REQUESTED** [review]
Let's not leave Django versions out unless we have a good reason.
Let's keep LooseVersion if possible.

File: newsletter/models.py
Comment (sebastian-muthwill) [reply newsletter/models.py:1]: TBH this part I was already in the Django-5 branch I based my changes on and I did not checked that. 
From what I see this is a patch in order to support Django versions <1.9. 
It would depend here on the general decision if such old versions need to be supported or not.

File: CHANGES.rst
Comment (sebastian-muthwill) [reply CHANGES.rst:1]: This is maybe more of a "philosophical" question. 
I try to follow in all my projects the release cycle of Python and Django and migrate the code base always at least to the latest LTS version. 
In general it becomes more and more challenging to support EOL versions because it requires patches for compatibility purpose and this effects the maintainability (like here: https://github.com/jazzband/django-newsletter/pull/394/files/d5300e560ad14dda0c625290236e00d7b98d86b7#diff-4d097d8e2ddb447f443dc2a92699225f61c2f7370d077988d93c83cc572d71f9)

**Comment by sebastian-muthwill** [comment]
I just saw that @dokterbob already released v1.0 to PyPi. 
May we have your opinion here as well. I think we should at least merge this PR to master as well to keep master and PyPi version in sync. 
After that we can discuss if older versions should be supported or not.

File: newsletter/models.py
Comment (newearthmartin) [reply newsletter/models.py:1]: It's not a good practice to leave commented lines. Please remove them.

And also there is no point in removing `LooseVersion` and then manually parsing the version. You can just revert that.

File: CHANGES.rst
Comment (newearthmartin) [reply CHANGES.rst:1]: I'm in favor of dropping support for older versions that require these patches. In that case we need to remove the patches, too. But that will not take us up to 4.2. We can support more versions.

Remember that this is not "your" or "my" project. I also keep my projects always on the latest versions, but this library has been around for many years and there may be many projects using older Django versions. We don't want to force them to upgrade unnecessarily.

**Comment by newearthmartin** [comment]
Before merging please address the code quality comments I made. Don't leave commented lines and remove the patches for older Django versions.

**Comment by adRn-s** [comment]
I don't know if I have a strict positioning on the matter, but I'd like to say that a new version of this package that drops support for, say, Django 1.9 is not necessarily wrong. Anyone running Django 1.9 could still use the old django-newsletter version that supports that. This is perfectly normal, expected, and I'd argue even desired (if it makes it easier on manteinance and new developments.)

**Comment by newearthmartin** [comment]
> if it makes it easier on manteinance and new developments.

My suggestion is to drop old versions when they conflict with development. Not before just because. When a new feature requires a higher version of Django, then support can be dropped.

**Comment by newearthmartin** [comment]
Hi @sebastian-muthwill it seems I forgot about this PR and went and duplicated your efforts on another PR to fix the automated build and tests https://github.com/jazzband/django-newsletter/pull/399

I now get the need to drop the older versions, but it's not just because they are old but because dependencies don't work, for example sorl-thumbanail needs django >= 4.

I did this because I made another PR https://github.com/jazzband/django-newsletter/pull/397 and tests were broken. 

Apparently no one cares about this anymore? Nobody is reviewing PRs, so what do you think we should do? Has anyone managed to contact @dokterbob ? Does anyone have rights to approve PRs?
