### ISSUE TITLE
Django 4.1 support?

### ISSUE THREAD

**Issue by jdbit** [jazzband/django-newsletter#383]
Hi,
The latest version of django-newsletter doesn't work with Django 4.1.
I got this error:

`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'`

I fixed it by replacing deprecated ugettext_lazy to gettext_lazy, but got another error which I don't know how to fix:

`ImportError: Module "compressor.finders" does not define a "CompressorFinder" attribute/class`

**Comment by nasir733** [comment]
Any Update on this ?

**Comment by gabn88** [comment]
@Bashar @jezdez Thank you for your work on this package. Would it be an idea to create a new release on PyPi? That would also close this issue.

**Comment by MiKatre** [comment]
The workaround for now is to install it directly from GitHub. It works with Django 4.1

I have this line in my Pipfile (I am using pipenv)
``` Pipfile
# Pipfile
django = "~=4.1"
django-newsletter = {git = "https://github.com/jazzband/django-newsletter.git", ref = "master"}
...
```

**Comment by jonnyhoff** [comment]
Any progress on this?

**Comment by jonnyhoff** [comment]
When using the Git Repo, everything works but not when installing the PyPi Package.

```shell
poetry add git+https://github.com/jazzband/django-newsletter.git
```

**Comment by thismatters** [comment]
Throwing it out there that I've just released a package to replace this one called [django-mailinglist](https://github.com/thismatters/django-mailinglist); it is fully django 4+ compliant!

**Comment by CARocha** [comment]
Wow, this error not resolves! Maybe @jazzband-bot need change the responsibility in this project not?

**Comment by newearthmartin** [comment]
I created another issue for adding testing and support for Python 3.11 and 3.12 and Django 4 and 5
https://github.com/jazzband/django-newsletter/issues/392

**Comment by newearthmartin** [comment]
And a PR to remove a deprecation warning in Python 3.12
https://github.com/jazzband/django-newsletter/pull/391

Hope this helps stir the waters and get some attention on this
